# Generated by Django 2.0.6 on 2018-07-29 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0002_auto_20180725_0541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ie',
            old_name='operators',
            new_name='operation_man',
        ),
        migrations.RenameField(
            model_name='ie',
            old_name='overtime',
            new_name='shift_man',
        ),
        migrations.RemoveField(
            model_name='ie',
            name='production',
        ),
        migrations.RemoveField(
            model_name='ie',
            name='sam_avaliable',
        ),
        migrations.RemoveField(
            model_name='ie',
            name='sam_earned',
        ),
        migrations.RemoveField(
            model_name='ie',
            name='style_sam',
        ),
        migrations.RemoveField(
            model_name='ie',
            name='working',
        ),
        migrations.AddField(
            model_name='ie',
            name='minutes_avaliable',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ie',
            name='minutes_earned',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ie',
            name='operation_hours',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ie',
            name='shift_hours',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ie',
            name='efficiency',
            field=models.FloatField(default=0),
        ),
    ]
