# Generated by Django 2.0.6 on 2018-08-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0003_auto_20180729_0635'),
    ]

    operations = [
        migrations.CreateModel(
            name='total',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=0)),
                ('january', models.IntegerField(default=0)),
                ('feb', models.IntegerField(default=0)),
                ('march', models.IntegerField(default=0)),
                ('april', models.IntegerField(default=0)),
                ('may', models.IntegerField(default=0)),
                ('june', models.IntegerField(default=0)),
                ('july', models.IntegerField(default=0)),
                ('august', models.IntegerField(default=0)),
                ('september', models.IntegerField(default=0)),
                ('octuber', models.IntegerField(default=0)),
                ('november', models.IntegerField(default=0)),
                ('december', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='ie',
            name='efficiency',
        ),
        migrations.RemoveField(
            model_name='ie',
            name='line',
        ),
        migrations.RemoveField(
            model_name='ie',
            name='minutes_avaliable',
        ),
        migrations.RemoveField(
            model_name='ie',
            name='minutes_earned',
        ),
        migrations.RemoveField(
            model_name='ie',
            name='operation_hours',
        ),
        migrations.RemoveField(
            model_name='ie',
            name='operation_man',
        ),
        migrations.RemoveField(
            model_name='ie',
            name='shift_man',
        ),
        migrations.RemoveField(
            model_name='ie',
            name='style_name',
        ),
        migrations.AddField(
            model_name='ie',
            name='description',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='ie',
            name='project',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
